### ISSUE TITLE
Cyclops image does not load

### ISSUE THREAD

**Issue by hengrv** [antixenoinitiative/axiwiki#10]
The Cyclops image on the "interceptors" page does not load. This could be due to the markdown looking for `cyclops-small.png` and the file in axiwiki/img being named `Cyclops-small.png` (note the capital letter).

![image](https://user-images.githubusercontent.com/66964414/123126847-a61fd980-d441-11eb-9cbf-9ae4c810597e.png)

**Comment by MgramTheDuck** [comment]
Capitalization Resolved
https://github.com/antixenoinitiative/axiwiki/commit/f79a0b509804db545545e84c5d04dcc93866fe52
