### ISSUE TITLE
All googleusercontent images return a 403 when attempting to access them. 

### ISSUE THREAD

**Issue by WillHof** [antixenoinitiative/axiwiki#11]
![Capture](https://user-images.githubusercontent.com/48184846/123153432-a5804680-d433-11eb-93af-c2bf661112cb.PNG)

Either:
> Host the images on the wiki (I could do this)

> Whitelist the new domain/enable google api access/other

**Comment by MgramTheDuck** [comment]
@WillHof let's go with the locally hosted approach.

To-do: 
- [ ] download all relevant images
- [ ] resize (<1MB) and upload to ./img/
- [ ] update image references on pages
