### ISSUE TITLE
Improve formatting on Thargoid Specs HTML Table

### ISSUE THREAD

**Issue by MgramTheDuck** [antixenoinitiative/axiwiki#15]
HTML layout is poor and not very clean, needs to be rewritten.

https://www.github.com/antixenoinitiative/axiwiki/tree/main/thargoid-specs.html

**Comment by hengrv** [comment]
hi, have been working on this, and almost done  - but there are some characters such as `§` and `†`, which would indicate footnotes but there are non - are they okay to remove

additionally, is it okay to fill all blank cells with N/A or is there a reason that they are blank?

**Comment by hengrv** [comment]
additionally, are there any stats on exerted heart regen speeds? the fields are empty for all interceptors?
![image](https://user-images.githubusercontent.com/66964414/124367001-ae4ef480-dc4b-11eb-8a75-e129ab2fcd7c.png)
