### ISSUE TITLE
CSS in HTML Files

### ISSUE THREAD

**Issue by MgramTheDuck** [antixenoinitiative/axiwiki#6]
HTML Files will need to be scrubbed of any CSS unless specifically needed.

This is an flow on affect of the migration.

CSS is provided by the Wiki.js platform itself, CSS is not needed in the HTML for each page.

**Comment by WillHof** [comment]
I can take this one

**Comment by WillHof** [comment]
Hi CMDRMgram, wanted to clarify a few points regarding 'specifically needed' before I merge and submit a PR. 

- Wiki.js doesn't have out-of-the-box CSS for iframe embeds, they pop up as small as possible. Are you planning on using the wiki.js CSS override to manage content like that (or custom per page, etc.), or should I add the inline CSS back?
- Inline CSS currently required for thargoid specs table, may be more trouble to fix up in wiki.js than it's worth. I see that there's an optional table module that can be enabled but that's something the site admin would have to do. 

contains iframes:
basic-combat-guide.html
buildrepository.html
cold-orbiting.html
mini-tot-calculator.html
synthesiscalculator.html 
guardianunlocks.html*
large-ship-guide.html*

*These two contained non-functional oembed links. I replaced that code to use iframes.

**Comment by MgramTheDuck** [comment]
@WillHof I can setup the Global CSS overrides for the Video embeds, this will make it easier to standardise the layout of embedded videos across the wiki. Something like this:

![image](https://user-images.githubusercontent.com/85346345/123206178-9ca87700-d4fe-11eb-9757-35abc7dda9a2.png)

Would you know how to make some CSS for this that I can add to the Global CSS Override? ie: 66% width, centered

I have created a new issue for the CSS in the Thargoid Spec Table as I believe this entire table needs an overhaul. Lets ignore it for now and we can have a look at the table module if this will be sufficient.

**Comment by WillHof** [comment]
> @WillHof I can setup the Global CSS overrides for the Video embeds, this will make it easier to standardise the layout of embedded videos across the wiki. Something like this:
> 
> ![image](https://user-images.githubusercontent.com/85346345/123206178-9ca87700-d4fe-11eb-9757-35abc7dda9a2.png)
> 
> Would you know how to make some CSS for this that I can add to the Global CSS Override? ie: 66% width, centered
> 
> I have created a new issue for the CSS in the Thargoid Spec Table as I believe this entire table needs an overhaul. Lets ignore it for now and we can have a look at the table module if this will be sufficient.

I'm not the best at CSS; but centered the iFrame and downscaled it. Reducing the vertical padding further starts clipping into the iFrame, as if it was still sized at 100%. It doesn't look too bad but the vertical gaps should be shorter, not sure how to fix it.

**Comment by MgramTheDuck** [comment]
All good, I'll work the the video CSS later, great work on this issue. I've committed the changes. Let's check out if it's working as intended.
